spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board?logger=com.mysql.cj.log.Slf4JLogger&profileSQL=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  config-location: classpath:mybatis-config.xml # MyBatis 설정 파일 경로 (Optional)
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.board.dto     # DTO 클래스 패키지
